# Generated by Django 3.2.5 on 2021-07-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postproperty',
            old_name='title',
            new_name='pg_name',
        ),
    ]
