# Generated by Django 3.2.5 on 2021-07-22 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_rename_title_postproperty_pg_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='postproperty',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
